name: Docker liatrio

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker login
      run: |
        docker login -u dockeruserst3v3 -p Test@12345
    - name: docker build
      run: |
        docker build  -t exercise
    - name: run tests
      uses: liatrio/github-actions/apprentice-action@master
    - name: Docker push
      run: |
        docker push
        # not done with last line
      
