name: Docker Series Builds

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: dockeruserst3v3
        DOCKER_PASSWORD: ${{ DOCKERHUB_USERPASS }}
      run: |
        docker login -u dockeruserst3v3 -p $DOCKER_PASSWORD
    - name: docker build
      run: |
        docker build  -t exercise
    - name: run tests
      uses: liatrio/github-actions/apprentice-action@master
    - name: Docker push
      run: |
        docker push
      
