<<<<<<< HEAD
name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: set up docker builddx
    - uses: docker/setup-buildx-action@v1
    - name: run liatrio tests
      run: echo hello
    - name: Login to dockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_USERPASS }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: user/app:latest


=======
# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
runs-on: ubuntu-latest
build-container:
    - name: Build Container, Test, and Push to Hub
  steps:
    - name: Build Container
      uses:

    - name: get files
      uses: 

    - name: run tests
      uses: liatrio/github-actions/apprentice-action@master

    - name: Push to Hub
      uses: 
        with: 
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_USERPASS }}
          repository: app/next
          tags: latest, ${{ github.run_number }}
>>>>>>> eb7d612700101130e290af52f8127e2dbeb33381
