# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build-container:
    name: Build Docker Container
    runs-on: ubuntu-latest
    steps:
      - name: See Code
        uses: actions/checkout@v3
 
      - name: Publish to DockerHub
        uses: dockerbuild@master
        with:
          username: ${{ secretes.DOCKERHUB_USERNAME }} 
          password: ${{ secrets.DOCKERHUB_USERPASS }}
          repository: app/next
          tags: latest, ${{ github.run_number }}
        
  build:
    runs-on: ubuntu-latest
    steps:
    - name: run tests
      uses: liatrio/github-actions/apprentice-action@master
  
