name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: set up docker builddx
    - uses: docker/setup-buildx-action@v1
    - name: run liatrio tests
      run: echo hello
    - name: Login to dockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_USERPASS }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: user/app:latest


