name: Docker Series Builds

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}   
        DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_USERPASS }}  
      run: |
        docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_USERPASS
    - name: docker build nodejs
      run: |
        docker build ./app -t minecraftst3v3/latest
