name: Docker liatrio

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker login
      run: |
        docker login -u dockeruserst3v3 -p Test@12345
    - name: docker build
      run: |
        docker build -t exercise https://github.com/MinecraftSt3v3/App-Exercise-Liatrio.git#main
    - name: docker run
      run: |
        docker run -p 80:80 -d exercise
    - name: run tests
      uses: liatrio/github-actions/apprentice-action@master
    - name: docker push
      run: |
        docker push exercise
