name: Docker Series Builds

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: dockeruserst3v3   
        DOCKER_PASSWORD: Steve@1699  
      run: |
        docker login -u dockeruserst3v3 -p Steve@1699
    - name: docker build nodejs
      run: |
        docker build ./app -t minecraftst3v3/latest
